# SPDX-FileCopyrightText: 2025 Digg - Agency for Digital Government
#
# SPDX-License-Identifier: CC0-1.0

# .rumdl.toml

[global]
# (optional) whatever else you have here

[per-file-ignores]
"{SECURITY.md,CODE_OF_CONDUCT.md,CONTRIBUTING.md,README.md,GUIDELINES.md}" = ["MD041"]
"README.md" = ["MD033", "MD036"]
"development/DEVELOPMENT.md" = ["MD051"]
"GUIDELINES.md" = ["MD007", "MD036", "MD052", "MD040", "MD005"]
