export class ProblemDetailsDTO {
    /**
     * A URI reference [RFC3986] that identifies the problem type.
     * This URI should provide human-readable documentation for the problem type.
     */
    type: string;
  
    /**
     * A short, human-readable summary of the problem type.
     * It should not change from occurrence to occurrence of the problem, except for localization purposes.
     */
    title: string;
  
    /**
     * The HTTP status code [RFC7231] generated by the origin server for this occurrence of the problem.
     */
    status: number;
  
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
  
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     * It may yield further information if dereferenced.
     */
    instance?: string;
  
    /**
     * Additional fields specific to the error, typically key-value pairs.
     */
    [key: string]: any;
  
    constructor(data: Partial<ProblemDetailsDTO>) {
      this.type = data.type ?? 'about:blank';
      this.title = data.title ?? 'An error occurred';
      this.status = data.status ?? 500;
      this.detail = data.detail;
      this.instance = data.instance;
  
      // Include any other fields in the object, allowing flexibility for extra properties
      Object.assign(this, data);
    }
  }
  