# SPDX-FileCopyrightText: 2025 diggsweden/rest-api-profil-lint-processor
#
# SPDX-License-Identifier: EUPL-1.2

---
name: RAP-LP project Workflow

on: # yamllint disable-line rule:truthy
  push:
    tags:
      - "v*.*.*"
jobs:
  # Skapar en release tag som är stabil.
  publish-package:
    if: ${{ github.ref_name =~ '^v[0-9]+\.[0-9]+\.[0-9]+$' }}
    uses: ./.github/workflows/publish-package.yaml
    permissions:
      contents: read
      packages: write
  publish-image:
    if: ${{ github.ref_name =~ '^v[0-9]+\.[0-9]+\.[0-9]+$' }}
    uses: ./.github/workflows/publish-image.yaml
    permissions:
      contents: read
      packages: write
